services:
  frontend:
    image: ${IMAGE_FULL}
    container_name: ${DEPLOY_CONTAINER}
    restart: unless-stopped
    ports:
      - "${PORT_HOST}:80"
    volumes:
      - nginx_logs:/var/log/nginx

volumes:
  nginx_logs:
